version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=H33blo@#!
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  heeblo:
    image: heeblo:latest
    links:
      - db:database
    ports:
      - '8000:80'
volumes:
  db:
    driver: local